### ISSUE TITLE
Syntax error: SELECT list must not be empty at [1:9]

### ISSUE THREAD

**Issue by Sthuliskandaba** [priyankavergadia/AppointmentScheduler-BigQuery#2]
When I try run the Query in BigQuery this is the error I get. Can someone please help

**Comment by eoaOsho** [comment]
I had similar challenge until is saw the solution as offered on red_Dit due credits to @CrazyRandomRunner on Red_Dit

This error appears when there is nothing between SELECT and FROM other than spaces. But the "SELECT FROM" format appears by default when you hit the QUERY link on a table and one has to manually enter the fields one is interested in between SELECT and FROM. If by chance you are using an iPad, the virtual keyboard does not automatically come up when you hit this link. You can hit the keyboard icon in the lower right and typing will be allowed but then the virtual keyboard will take up most of the screen. A Bluetooth keyboard is better, though it is not perfect. (Neither my iPad virtual keyboard nor my Bluetooth keyboard directly supports typing the all-important backtick character, so I use a laptop instead.)

If you are using a different mobile device other than an iPad, you may be running into a variation of the same problem.


This error appears when there is nothing between SELECT and FROM other than spaces. But the "SELECT FROM" format appears by default when you hit the QUERY link on a table and one has to manually enter the fields one is interested in between SELECT and FROM. If by chance you are using an iPad, the virtual keyboard does not automatically come up when you hit this link. You can hit the keyboard icon in the lower right and typing will be allowed but then the virtual keyboard will take up most of the screen. A Bluetooth keyboard is better, though it is not perfect. (Neither my iPad virtual keyboard nor my Bluetooth keyboard directly supports typing the all-important backtick character, so I use a laptop instead.)

If you are using a different mobile device other than an iPad, you may be running into a variation of the same problem.

This error appears when there is nothing between SELECT and FROM other than spaces. But the "SELECT FROM" format appears by default when you hit the QUERY link on a table and one has to manually enter the fields one is interested in between SELECT and FROM. If by chance you are using an iPad, the virtual keyboard does not automatically come up when you hit this link. You can hit the keyboard icon in the lower right and typing will be allowed but then the virtual keyboard will take up most of the screen. A Bluetooth keyboard is better, though it is not perfect. (Neither my iPad virtual keyboard nor my Bluetooth keyboard directly supports typing the all-important backtick character, so I use a laptop instead.)

If you are using a different mobile device other than an iPad, you may be running into a variation of the same problem.

If this problem occurs on a system them you can try changing your browser
