### ISSUE TITLE
This table is empty. BigQuery Cloud Console

### ISSUE THREAD

**Issue by Sthuliskandaba** [priyankavergadia/AppointmentScheduler-BigQuery#3]
I followed everything in the tutorial, however when I run the Select * from command on my console. There is no data that appears, please assist

{
  "textPayload": "Error: No responses defined for platform: DIALOGFLOW_CONSOLE\n    at WebhookClient.send_ (/workspace/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:488:13)\n    at promise.then (/workspace/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:306:38)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
  "insertId": "000000-f070a5ef-a9bb-4d60-88b1-0889435fee9e",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "function_name": "dialogflowFirebaseFulfillment",
      "project_id": "appointmentscheduler-cyrx",
      "region": "us-central1"
    }
  },
  "timestamp": "2021-03-20T10:42:16.917Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "twz9fpjgt499"
  },
  "logName": "projects/appointmentscheduler-cyrx/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/appointmentscheduler-cyrx/traces/d0d60635d1cd817ff50b6e9f04f442ba",
  "receiveTimestamp": "2021-03-20T10:42:17.728123527Z"
}

**Comment by SRIDEVI24** [comment]
even i get the same error.any help?
